version: '3.7'

services:
    # Jupyter server
    workspace:
        build: ./mlworkspace
        image: mlworkspace_server
        container_name: workspace_server
        volumes:
            - ${WORKSPACE_FOLDER}:${CONTAINER_WORKSPACE_FOLDER}
            - ${WORKSPACE_DATA_FOLDER}:${CONTAINER_WORKSPACE_FOLDER}/data
        expose:
            - "${JUPYTER_PORT}"
        networks:
            - workspace_network
        environment:
            AWS_ACCESS_KEY_ID: '${MINIO_ROOT_USER}'
            AWS_SECRET_ACCESS_KEY: '${MINIO_ROOT_PASSWORD}'
            MLFLOW_S3_ENDPOINT_URL: 'http://${S3_ENDPOINT}:${MINIO_PORT}'
            MLFLOW_TRACKING_URI: 'http://${TRACKING_ENDPOINT}:${MLFLOW_PORT}'
            MLFLOW_S3_IGNORE_TLS: '${MLFLOW_S3_IGNORE_TLS}'

    # Artifact server
    minio1:
        image: minio/minio:RELEASE.2021-04-22T15-44-28Z
        container_name: artifact_server
        volumes:
            - ${ARTIFACTS_FOLDER}:/data
        expose:
            - "${MINIO_PORT}"
        networks:
            - workspace_network
        environment:
            MINIO_ROOT_USER: '${MINIO_ROOT_USER}'
            MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD}'
        command: server /data
    
    # MLFLow server
    mlf:
        restart: always
        build: ./mlflow
        image: mlflow_server
        container_name: mlflow_server
        expose:
            - "${MLFLOW_PORT}"
        networks:
            - workspace_network
        environment:
            AWS_ACCESS_KEY_ID: '${MINIO_ROOT_USER}'
            AWS_SECRET_ACCESS_KEY: '${MINIO_ROOT_PASSWORD}'
            MLFLOW_S3_ENDPOINT_URL: 'http://${S3_ENDPOINT}:${MINIO_PORT}/'

        command: mlflow server --backend-store-uri sqlite:////mlruns/mlruns.db --default-artifact-root s3://mlflow --host 0.0.0.0
        volumes:
            - ${MLFLOW_FOLDER}:/mlruns
        depends_on:
            - minio1
            - workspace
    
    # Reverse proxy
    nginx:
        restart: always
        build: ./nginx
        image: mlflow_nginx
        container_name: mlflow_nginx
        ports:
            - "${EXPOSE_JUPYTER_PORT}:80"
            - "${EXPOSE_MLFLOW_PORT}:${MLFLOW_PORT}"
            - "${EXPOSE_MINIO_PORT}:${MINIO_PORT}"
        networks:
            - workspace_network
        depends_on:
            - minio1
            - mlf
            - workspace

networks:
    workspace_network:
        driver: bridge